---
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5
    steps:
    - checkout
    - restore_cache:
        keys:
          - v1-bundle-{{ checksum "Gemfile.lock" }}
          - v1-bundle-
    - run: bundle install --path vendor/bundle
    - save_cache:
        key: v1-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
    - run: make build
    - run: make serve &
    - run: make test
    - persist_to_workspace:
        root: .
        paths:
          - _site

  deploy:
    docker:
      - image: circleci/python:3
    environment:
      AWS_DEFAULT_REGION=us-west-2
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: pip install --user --upgrade awscli
    - run: aws s3 sync _site s3://beta.aws.openoakland.org/


workflows:
  version: 2
  commit:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
